name: Verify Attestations

on:
  push:

permissions:
  contents: read

jobs:
  audit:
    name: Verify signatures and provenance statements
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Run audit
        run: npm audit signatures
